import { api } from "./api";
import { AttendanceRecord } from "@/types/billing";

export const attendanceService = {
  getAttendance: async (): Promise<AttendanceRecord[]> => {
    const response = await api.get("/api/attendance");
    return response.data;
  },

  submitAttendance: async (records: AttendanceRecord[]): Promise<AttendanceRecord[]> => {
    // Strip the string 'id' field generated by the frontend so the backend doesn't 
    // throw a NumberFormatException trying to parse it into a Long.
    const payload = records.map(({ id, ...rest }) => rest);
    const response = await api.post("/api/attendance/submit", payload);
    return response.data;
  }
};
